// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"heartbeat.mdx": () => import("../content/docs/heartbeat.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "quickstart.mdx": () => import("../content/docs/quickstart.mdx?collection=docs"), "security-model.mdx": () => import("../content/docs/security-model.mdx?collection=docs"), "state-machine.mdx": () => import("../content/docs/state-machine.mdx?collection=docs"), "cli/call.mdx": () => import("../content/docs/cli/call.mdx?collection=docs"), "cli/cancel.mdx": () => import("../content/docs/cli/cancel.mdx?collection=docs"), "cli/create.mdx": () => import("../content/docs/cli/create.mdx?collection=docs"), "cli/get.mdx": () => import("../content/docs/cli/get.mdx?collection=docs"), "cli/index.mdx": () => import("../content/docs/cli/index.mdx?collection=docs"), "cli/init.mdx": () => import("../content/docs/cli/init.mdx?collection=docs"), "cli/list.mdx": () => import("../content/docs/cli/list.mdx?collection=docs"), "cli/pause.mdx": () => import("../content/docs/cli/pause.mdx?collection=docs"), "cli/resume.mdx": () => import("../content/docs/cli/resume.mdx?collection=docs"), "cli/send.mdx": () => import("../content/docs/cli/send.mdx?collection=docs"), "cli/start.mdx": () => import("../content/docs/cli/start.mdx?collection=docs"), "cli/status.mdx": () => import("../content/docs/cli/status.mdx?collection=docs"), "cli/stop.mdx": () => import("../content/docs/cli/stop.mdx?collection=docs"), "cli/telegram-login.mdx": () => import("../content/docs/cli/telegram-login.mdx?collection=docs"), "cli/telegram-logout.mdx": () => import("../content/docs/cli/telegram-logout.mdx?collection=docs"), "cli/telegram-status.mdx": () => import("../content/docs/cli/telegram-status.mdx?collection=docs"), "cli/transcript.mdx": () => import("../content/docs/cli/transcript.mdx?collection=docs"), "cli/whatsapp-login.mdx": () => import("../content/docs/cli/whatsapp-login.mdx?collection=docs"), "cli/whatsapp-logout.mdx": () => import("../content/docs/cli/whatsapp-logout.mdx?collection=docs"), "cli/whatsapp-status.mdx": () => import("../content/docs/cli/whatsapp-status.mdx?collection=docs"), }),
};
export default browserCollections;